import fs from 'node:fs';
import vm from 'node:vm';
import { describe, expect, it, vi } from 'vitest';
import { bootstrap } from '../src/game/bootstrap.node.ts';
import { Game } from '../src/game/game.ts';
import { BuildingHost } from '../src/host/building.ts';
import { GameEnums } from '../src/host/enums.ts';
import { CoreAI } from '../src/ai/cw/coreai.ts';
import { NORMAL_AI_DEFAULTS } from '../src/ai/cw/config.ts';
import { ProductionSystem } from '../src/ai/cw/production.ts';
import { applyAction } from '../src/ai/actions.ts';

const { createMap, registry, animations } = bootstrap();
function fixture(factoryXs = [1], width = 15) {
  const map = createMap(width, 3, 'PLAINS');
  const player = map.addPlayer('os'), enemy = map.addPlayer('bm');
  player.team = 0; enemy.team = 1;
  const game = new Game(map, registry, animations);
  const buildings = factoryXs.map(x => {
    const building = new BuildingHost(map, 'FACTORY', player);
    building.setTerrain(map.getTerrain(x, 1));
    map.getTerrain(x, 1).building = building;
    building.init();
    return building;
  });
  const hostile = map.addUnit('HEAVY_TANK', enemy, 0, 0);
  const core = new CoreAI(game, player, { ...NORMAL_AI_DEFAULTS });
  player.funds = 10000;
  const production = new ProductionSystem(() => 0.25);
  return { map, game, player, enemy, hostile, core, buildings, production };
}

function upstreamPolicy() {
  const raw = fs.readFileSync('ext/Commander_Wars/resources/aidata/normal/__coreai.js', 'utf8');
  const context = vm.createContext({ GameEnums });
  vm.runInContext(raw.replace('highPrioBuildings = [', 'highPrioBuildings : ['), context);
  return context.COREAI;
}

describe('pinned production policy', () => {
  it('ships the exact pinned JS with only the declared syntax and module adapters', () => {
    const raw = fs.readFileSync('ext/Commander_Wars/resources/aidata/normal/__coreai.js', 'utf8');
    const emitted = fs.readFileSync('src/ai/cw/production-policy.ts', 'utf8');
    expect(emitted).toBe('// @ts-nocheck\n// GENERATED by tools/gen_cw_production_policy.py; do not edit.\n'
      + '// Pinned Commander Wars __coreai.js, with only its object-literal syntax repaired.\n'
      + "import { GameEnums } from '../../host/enums.ts';\n\n"
      + raw.replace('highPrioBuildings = [', 'highPrioBuildings : [') + '\nexport { COREAI as PRODUCTION_POLICY };\n');
  });

  it.each([[1, 10000, 1], [7, 18000, 2], [12, 40000, 3]])(
    'matches upstream funds/phase callback for day %i, funds %i, factories %i', (day, funds, count) => {
      const { game, core, buildings, production, player } = fixture([1, 7, 13].slice(0, count));
      game.day = day; player.funds = funds;
      const call = vi.spyOn(production, 'buildNextUnit').mockReturnValue({ kind: 'build', at: { x: 1, y: 1 }, unitId: 'INFANTRY' });
      production.chooseAction(game, core, buildings, [], []);
      const reference: number[][] = [];
      upstreamPolicy().buildUnitSimpleProductionSystem({
        getVariables: () => ({}), getCurrentTurnProducedUnitsCounter: () => 0,
        buildNextUnit: (_b: unknown, _u: unknown, min: number, max: number, _island: number, minCost: number, maxCost: number) => {
          reference.push([min, max, minCost, maxCost]); return true;
        },
      }, { getPlayer: () => ({ getFunds: () => funds }) }, { getBuildingGroupCount: () => count }, {}, {}, {}, { getCurrentDay: () => day });
      expect(call.mock.calls.map(args => args.slice(5, 9))).toEqual(reference);
    });

  it('prefers a safe factory and falls back to a threatened factory when none are safe', () => {
    const { game, core, buildings, production, hostile } = fixture([1, 13]);
    const safe = production.chooseAction(game, core, buildings, [hostile], []);
    expect(safe).toMatchObject({ kind: 'build', at: { x: 13, y: 1 }, unitId: 'INFANTRY' });
    expect(applyAction(game, safe!)).toBe(true);
    const fallback = production.chooseAction(game, core, buildings, [hostile], []);
    expect(fallback).toMatchObject({ kind: 'build', at: { x: 1, y: 1 }, unitId: 'INFANTRY' });
    expect(applyAction(game, fallback!)).toBe(true);
  });

  it('does not use hidden enemies to choose a safer build location', () => {
    const { map, game, core, player, hostile, buildings, production } = fixture([1, 13]);
    map.getGameRules().setFogMode(GameEnums.Fog_OfWar);
    map.setTerrainID(hostile.x, hostile.y, 'FOREST');
    map.vision.update();
    expect(hostile.isStealthed(player)).toBe(true);
    expect(production.chooseAction(game, core, buildings, [hostile], []))
      .toMatchObject({ kind: 'build', at: { x: 1, y: 1 } });
  });

  it('resumes purchase count and opening queue within the same production turn', () => {
    const { game, core, player, buildings, production } = fixture([1, 13]);
    const first = production.chooseAction(game, core, buildings, [], []);
    expect(first?.kind).toBe('build');
    expect(applyAction(game, first!)).toBe(true);
    const saved = JSON.parse(JSON.stringify(production.saveState()));
    expect(saved.producedCount).toBe(1);
    expect(saved.initialProduction[0].count).toBe(5);
    const resumed = new ProductionSystem(() => 0.25);
    resumed.loadState(saved, player, buildings);
    const next = resumed.chooseAction(game, core, buildings, [], []);
    expect(next?.kind).toBe('build');
    expect(applyAction(game, next!)).toBe(true);
    expect(resumed.saveState()).toMatchObject({ producedCount: 2,
      preparedForTurn: '1:0', initialProduction: [{ unitIds: ['INFANTRY'], count: 4 }] });
  });

  it('applies the relative-island threshold instead of buying a stranded piperunner', () => {
    const isolated = fixture([1], 80);
    isolated.player.funds = 50000;
    expect(isolated.production.chooseAction(isolated.game, isolated.core, isolated.buildings, [], [],
      (_at, id) => id === 'PIPERUNNER')).toBeNull();
    const connected = fixture([1], 80);
    connected.player.funds = 50000;
    for (let x = 2; x <= 12; x++) connected.map.setTerrainID(x, 1, 'PIPELINE');
    expect(connected.production.chooseAction(connected.game, connected.core, connected.buildings, [], [],
      (_at, id) => id === 'PIPERUNNER')).toMatchObject({ kind: 'build', unitId: 'PIPERUNNER' });
  });


  it('upgrades older table-only saves without restarting their opening queue', () => {
    const { player, buildings, production } = fixture();
    production.initialize(player, buildings);
    const legacy = JSON.parse(JSON.stringify(production.saveState()));
    delete legacy.variables;
    delete legacy.preparedForTurn;
    legacy.initialProduction[0].count = 3;
    legacy.buildDistribution.find(([name]: [string]) => name === 'INFANTRY_GROUP')[1].distribution = 10;
    const resumed = new ProductionSystem(() => 0.25);
    resumed.loadState(legacy, player, buildings);
    const saved = resumed.saveState() as any;
    expect(saved.initialProduction[0].count).toBe(3);
    expect(saved.buildDistribution.find(([name]: [string]) => name === 'INFANTRY_GROUP')[1].distribution).toBe(40);
  });

});
