// GENERATED by tools/gen_cw_ai_config.py -- do not edit by hand.
//
// Commander Wars' NormalAi tunables: defaults from the m_iniData table in
// ai/normalai.cpp, overridden by resources/aidata/normal/normal.ini, which is
// the profile the shipping game plays on.

/** One tunable, with the bounds randomize() mutates it between. */
export interface IniRange {
  /** Key as it appears in the .ini file. */
  readonly name: string;
  /** .ini section. */
  readonly group: string;
  /** Field on NormalAiConfig this writes through to. */
  readonly field: keyof NormalAiConfig;
  readonly min: number;
  readonly max: number;
}

export interface NormalAiConfig {
  additionalLoadingUnitBonus: number;
  ammoResupply: number;
  antiCaptureBonus: number;
  antiCaptureBonusScoreDivider: number;
  antiCaptureBonusScoreReduction: number;
  antiCaptureHqBonus: number;
  attackCountBonus: number;
  averageSupplySupport: number;
  buildingBonusMultiplier: number;
  buildingValue: number;
  canSupplyBonus: number;
  cappedFunds: number;
  cappingFunds: number;
  cheapUnitBonusMultiplier: number;
  cheapUnitRatio: number;
  cheapUnitValue: number;
  coUnitBuffBonus: number;
  coUnitRankReduction: number;
  coUnitScoreMultiplier: number;
  coUnitValue: number;
  counterDamageBonus: number;
  counterUnitRatio: number;
  currentlyNotAttackableBonus: number;
  currentlyNotAttackableScoreBonus: number;
  damageToUnitCostRatioBonus: number;
  differentIslandBonusInRangeDays: number;
  differentIslandOutOfDayMalusFactor: number;
  directIndirectRatio: number;
  directIndirectUnitBonusFactor: number;
  earlyGame: number;
  enemyCounterDamageMultiplier: number;
  enemyIndirectBonus: number;
  enemyKillBonus: number;
  enemyPruneRange: number;
  enemyUnitCountDamageReductionMultiplier: number;
  expensiveUnitBonusMultiplier: number;
  flyingTransporterBonus: number;
  fuelResupply: number;
  fundsPerBuildingFactorA: number;
  fundsPerBuildingFactorB: number;
  fundsPerBuildingFactorC: number;
  fundsPerBuildingFactorD: number;
  highDamage: number;
  highDamageBonus: number;
  highDirectMalus: number;
  highIndirectMalus: number;
  indirectUnitAttackCountMalus: number;
  influenceIgnoreValue: number;
  influenceMultiplier: number;
  influenceUnitRange: number;
  lockedUnitHp: number;
  lowDamageBonus: number;
  lowDirectMalus: number;
  lowIncomeInfantryBonusMultiplier: number;
  lowIndirectMalus: number;
  lowIndirectUnitBonus: number;
  lowInfantryRatio: number;
  lowOwnBuildingEnemyBuildingRatio: number;
  lowThreadDamage: number;
  maxCloseDistanceDamageBonus: number;
  maxDayScoreVariancer: number;
  maxDistanceMultiplier: number;
  maxOverkillBonus: number;
  maxProductionBuildings: number;
  maxProductionBuildingsForB: number;
  maxSupplyUnitRatio: number;
  maxUnitHealth: number;
  midDamage: number;
  midDamageBonus: number;
  minAttackCountBonus: number;
  minAttackFunds: number;
  minCloseDistanceDamageBonus: number;
  minCoUnitCount: number;
  minCoUnitScore: number;
  minFlyingTransportScoreForBonus: number;
  minHpDamage: number;
  minInfantryCount: number;
  minMovementDamage: number;
  minSameIslandDistance: number;
  minSiloDamage: number;
  minSuicideDamage: number;
  minTerrainDamage: number;
  minUnitCountForDamageBonus: number;
  minUnitHealth: number;
  movementpointBonus: number;
  nearEnemyBonus: number;
  noMoveAttackHp: number;
  noTransporterBonus: number;
  normalUnitBonusMultiplier: number;
  normalUnitRatio: number;
  notAttackableDamage: number;
  ownBuildingPruneRange: number;
  ownIndirectAttackValue: number;
  ownProdctionMalus: number;
  ownUnitEnemyUnitRatioAverager: number;
  ownUnitValue: number;
  producingTransportLoadingBonus: number;
  producingTransportMinLoadingTransportRatio: number;
  producingTransportRatioBonus: number;
  producingTransportSearchrange: number;
  producingTransportSizeBonus: number;
  sameFundsMatchUpBonus: number;
  sameFundsMatchUpMovementMalus: number;
  sameFundsMatchUpNoMatchUpValue: number;
  sameIslandBonusInRangeDays: number;
  sameIslandOutOfDayMalusFactor: number;
  scoringCutOffDamageHigh: number;
  scoringCutOffDamageLow: number;
  slowUnitSpeed: number;
  smallTransporterBonus: number;
  smoothingValue: number;
  spamInfantryChance: number;
  spamLightUnitChance: number;
  spamMediumUnitChance: number;
  spamingFunds: number;
  startDayScoreVariancer: number;
  superiorityRatio: number;
  supportDamageBonus: number;
  targetPriceDifference: number;
  transportBonus: number;
  transporterToRequiredPlaceFactor: number;
  turnOneDmageMalus: number;
  unitToSmallTransporterRatio: number;
  veryLowDamageBonus: number;
  watermineDamage: number;
}

/**
 * Upstream aliases these .ini keys onto one field, so the last one read wins:
 *   highIndirectMalus <- HighIndirectMalus, LowDirectUnitBonus
 *
 * That is an upstream pointer mix-up rather than a design, but the shipping
 * game plays on the resulting value, so the port keeps it.
 */
export const NORMAL_AI_DEFAULTS: NormalAiConfig = {
  additionalLoadingUnitBonus: 5,
  ammoResupply: 0.12,
  antiCaptureBonus: 10,
  antiCaptureBonusScoreDivider: 4,
  antiCaptureBonusScoreReduction: 8,
  antiCaptureHqBonus: 1000,
  attackCountBonus: 25,
  averageSupplySupport: 7.28,
  buildingBonusMultiplier: 6.24,
  buildingValue: 1,
  canSupplyBonus: 14.2,
  cappedFunds: 1000,
  cappingFunds: 6500,
  cheapUnitBonusMultiplier: 10,
  cheapUnitRatio: 0.2,
  cheapUnitValue: 1200,
  coUnitBuffBonus: 7,
  coUnitRankReduction: 1100,
  coUnitScoreMultiplier: 2.45,
  coUnitValue: 6000,
  counterDamageBonus: 30,
  counterUnitRatio: 2,
  currentlyNotAttackableBonus: 1,
  currentlyNotAttackableScoreBonus: 50,
  damageToUnitCostRatioBonus: 35,
  differentIslandBonusInRangeDays: 1,
  differentIslandOutOfDayMalusFactor: 0.66,
  directIndirectRatio: 3.5,
  directIndirectUnitBonusFactor: 1,
  earlyGame: 5,
  enemyCounterDamageMultiplier: 10,
  enemyIndirectBonus: 0.9,
  enemyKillBonus: 1.2,
  enemyPruneRange: 3,
  enemyUnitCountDamageReductionMultiplier: 6,
  expensiveUnitBonusMultiplier: 30,
  flyingTransporterBonus: 15,
  fuelResupply: 0.3,
  fundsPerBuildingFactorA: 1.625,
  fundsPerBuildingFactorB: 3,
  fundsPerBuildingFactorC: 2.5,
  fundsPerBuildingFactorD: 1.25,
  highDamage: 75,
  highDamageBonus: 1.4,
  highDirectMalus: 67,
  highIndirectMalus: 37.67,
  indirectUnitAttackCountMalus: 4,
  influenceIgnoreValue: 0.75,
  influenceMultiplier: 0.8,
  influenceUnitRange: 2.25,
  lockedUnitHp: 3.24,
  lowDamageBonus: 1,
  lowDirectMalus: 15,
  lowIncomeInfantryBonusMultiplier: 29.4,
  lowIndirectMalus: 13,
  lowIndirectUnitBonus: 42,
  lowInfantryRatio: 0.2,
  lowOwnBuildingEnemyBuildingRatio: 1.5,
  lowThreadDamage: 10,
  maxCloseDistanceDamageBonus: 1,
  maxDayScoreVariancer: 16,
  maxDistanceMultiplier: 1.5,
  maxOverkillBonus: 2,
  maxProductionBuildings: 4,
  maxProductionBuildingsForB: 1,
  maxSupplyUnitRatio: 0.01,
  maxUnitHealth: 4.5,
  midDamage: 45,
  midDamageBonus: 1,
  minAttackCountBonus: 4.2,
  minAttackFunds: 0,
  minCloseDistanceDamageBonus: 0.2,
  minCoUnitCount: 4.5,
  minCoUnitScore: 5000,
  minFlyingTransportScoreForBonus: 15,
  minHpDamage: -2,
  minInfantryCount: 5,
  minMovementDamage: 0.15,
  minSameIslandDistance: 2.25,
  minSiloDamage: 7000,
  minSuicideDamage: 0.1,
  minTerrainDamage: 20,
  minUnitCountForDamageBonus: 4,
  minUnitHealth: 2.8,
  movementpointBonus: 5,
  nearEnemyBonus: 4,
  noMoveAttackHp: 2,
  noTransporterBonus: 70,
  normalUnitBonusMultiplier: 30,
  normalUnitRatio: 1,
  notAttackableDamage: 30,
  ownBuildingPruneRange: 10,
  ownIndirectAttackValue: 4,
  ownProdctionMalus: 10000,
  ownUnitEnemyUnitRatioAverager: 12,
  ownUnitValue: 1,
  producingTransportLoadingBonus: 10,
  producingTransportMinLoadingTransportRatio: 10,
  producingTransportRatioBonus: 10,
  producingTransportSearchrange: 6,
  producingTransportSizeBonus: 15,
  sameFundsMatchUpBonus: 40,
  sameFundsMatchUpMovementMalus: 0.3,
  sameFundsMatchUpNoMatchUpValue: 0.5,
  sameIslandBonusInRangeDays: 1.75,
  sameIslandOutOfDayMalusFactor: 0.15,
  scoringCutOffDamageHigh: 100,
  scoringCutOffDamageLow: 7.8,
  slowUnitSpeed: 2,
  smallTransporterBonus: 30,
  smoothingValue: 4,
  spamInfantryChance: 30,
  spamLightUnitChance: 75,
  spamMediumUnitChance: 15,
  spamingFunds: 8000,
  startDayScoreVariancer: 5,
  superiorityRatio: 2.2,
  supportDamageBonus: 0.8,
  targetPriceDifference: 0.2,
  transportBonus: 0.11,
  transporterToRequiredPlaceFactor: 6,
  turnOneDmageMalus: 10,
  unitToSmallTransporterRatio: 5,
  veryLowDamageBonus: 1,
  watermineDamage: 4,
};

/**
 * Mutation bounds, straight from the C++ table.
 *
 * CoreAI::randomizeIni rolls each knob inside its range to make a family of
 * distinct opponents out of one AI. Note a few upstream ranges are degenerate
 * (min above max, defaults outside the range); they are transcribed as-is and
 * randomize() orders each pair before sampling.
 */
export const INI_RANGES: readonly IniRange[] = [
  { name: 'MinMovementDamage', group: 'General', field: 'minMovementDamage', min: -1, max: 1 },
  { name: 'MinAttackFunds', group: 'General', field: 'minAttackFunds', min: -1, max: 1 },
  { name: 'MinSuicideDamage', group: 'General', field: 'minSuicideDamage', min: -1, max: 1 },
  { name: 'SpamingFunds', group: 'General', field: 'spamingFunds', min: 5000, max: 10000 },
  { name: 'OwnUnitValue', group: 'General', field: 'ownUnitValue', min: -10, max: 10 },
  { name: 'BuildingValue', group: 'General', field: 'buildingValue', min: 1, max: 1 },
  { name: 'NotAttackableDamage', group: 'General', field: 'notAttackableDamage', min: 0, max: 40 },
  { name: 'MidDamage', group: 'General', field: 'midDamage', min: 40, max: 60 },
  { name: 'HighDamage', group: 'General', field: 'highDamage', min: 60, max: 100 },
  { name: 'DirectIndirectRatio', group: 'General', field: 'directIndirectRatio', min: 0.2, max: 10 },
  { name: 'MinSiloDamage', group: 'General', field: 'minSiloDamage', min: 7000, max: 7000 },
  { name: 'MinSameIslandDistance', group: 'General', field: 'minSameIslandDistance', min: 3, max: 3 },
  { name: 'SlowUnitSpeed', group: 'General', field: 'slowUnitSpeed', min: 2, max: 2 },
  { name: 'EnemyPruneRange', group: 'General', field: 'enemyPruneRange', min: 1, max: 5 },
  { name: 'CoUnitValue', group: 'CoUnit', field: 'coUnitValue', min: 5000, max: 20000 },
  { name: 'MinCoUnitScore', group: 'CoUnit', field: 'minCoUnitScore', min: 3000, max: 20000 },
  { name: 'CoUnitRankReduction', group: 'CoUnit', field: 'coUnitRankReduction', min: 0, max: 5000 },
  { name: 'CoUnitScoreMultiplier', group: 'CoUnit', field: 'coUnitScoreMultiplier', min: 1, max: 3 },
  { name: 'MinCoUnitCount', group: 'CoUnit', field: 'minCoUnitCount', min: 1, max: 10 },
  { name: 'MinUnitHealth', group: 'Repairing', field: 'minUnitHealth', min: 0, max: 10 },
  { name: 'MaxUnitHealth', group: 'Repairing', field: 'maxUnitHealth', min: 0, max: 10 },
  { name: 'FuelResupply', group: 'Repairing', field: 'fuelResupply', min: 0, max: 0.7 },
  { name: 'AmmoResupply', group: 'Repairing', field: 'ammoResupply', min: 0, max: 0.7 },
  { name: 'LockedUnitHp', group: 'Moving', field: 'lockedUnitHp', min: 1, max: 10 },
  { name: 'NoMoveAttackHp', group: 'Moving', field: 'noMoveAttackHp', min: 1, max: 10 },
  { name: 'MinTerrainDamage', group: 'Moving', field: 'minTerrainDamage', min: 20, max: 20 },
  { name: 'InfluenceUnitRange', group: 'Moving', field: 'influenceUnitRange', min: 1, max: 5 },
  { name: 'OwnIndirectAttackValue', group: 'Attacking', field: 'ownIndirectAttackValue', min: 0.1, max: 10 },
  { name: 'EnemyKillBonus', group: 'Attacking', field: 'enemyKillBonus', min: 0.1, max: 10 },
  { name: 'EnemyIndirectBonus', group: 'Attacking', field: 'enemyIndirectBonus', min: 0.1, max: 10 },
  { name: 'AntiCaptureHqBonus', group: 'Attacking', field: 'antiCaptureHqBonus', min: 0, max: 10000 },
  { name: 'AntiCaptureBonus', group: 'Attacking', field: 'antiCaptureBonus', min: 0, max: 100 },
  { name: 'AntiCaptureBonusScoreReduction', group: 'Attacking', field: 'antiCaptureBonusScoreReduction', min: 0, max: 200 },
  { name: 'AntiCaptureBonusScoreDivider', group: 'Attacking', field: 'antiCaptureBonusScoreDivider', min: 0.1, max: 10 },
  { name: 'EnemyCounterDamageMultiplier', group: 'Attacking', field: 'enemyCounterDamageMultiplier', min: 0.1, max: 40 },
  { name: 'WatermineDamage', group: 'Attacking', field: 'watermineDamage', min: 4, max: 4 },
  { name: 'EnemyUnitCountDamageReductionMultiplier', group: 'Attacking', field: 'enemyUnitCountDamageReductionMultiplier', min: 0.01, max: 10 },
  { name: 'OwnProdctionMalus', group: 'Attacking', field: 'ownProdctionMalus', min: 5000, max: 50000 },
  { name: 'SupportDamageBonus', group: 'Attacking', field: 'supportDamageBonus', min: 0.1, max: 10 },
  { name: 'InfluenceIgnoreValue', group: 'Attacking', field: 'influenceIgnoreValue', min: 0.01, max: 1 },
  { name: 'InfluenceMultiplier', group: 'Attacking', field: 'influenceMultiplier', min: 0.1, max: 10 },
  { name: 'MinHpDamage', group: 'Attacking', field: 'minHpDamage', min: -10, max: 0 },
  { name: 'FundsPerBuildingFactorA', group: 'Production', field: 'fundsPerBuildingFactorA', min: 0.5, max: 10 },
  { name: 'FundsPerBuildingFactorB', group: 'Production', field: 'fundsPerBuildingFactorB', min: 0.5, max: 10 },
  { name: 'FundsPerBuildingFactorC', group: 'Production', field: 'fundsPerBuildingFactorC', min: 1, max: 10 },
  { name: 'FundsPerBuildingFactorD', group: 'Production', field: 'fundsPerBuildingFactorD', min: 1, max: 10 },
  { name: 'OwnUnitEnemyUnitRatioAverager', group: 'Production', field: 'ownUnitEnemyUnitRatioAverager', min: 5, max: 30 },
  { name: 'MaxDayScoreVariancer', group: 'Production', field: 'maxDayScoreVariancer', min: 5, max: 30 },
  { name: 'StartDayScoreVariancer', group: 'Production', field: 'startDayScoreVariancer', min: 0, max: 15 },
  { name: 'DirectIndirectUnitBonusFactor', group: 'Production', field: 'directIndirectUnitBonusFactor', min: 0.1, max: 10 },
  { name: 'ScoringCutOffDamageHigh', group: 'Production', field: 'scoringCutOffDamageHigh', min: 100, max: 100 },
  { name: 'ScoringCutOffDamageLow', group: 'Production', field: 'scoringCutOffDamageLow', min: 0.1, max: 40 },
  { name: 'SmoothingValue', group: 'Production', field: 'smoothingValue', min: 1, max: 20 },
  { name: 'MaxDistanceMultiplier', group: 'Production', field: 'maxDistanceMultiplier', min: 1, max: 10 },
  { name: 'SameIslandBonusInRangeDays', group: 'Production', field: 'sameIslandBonusInRangeDays', min: 1, max: 10 },
  { name: 'SameIslandOutOfDayMalusFactor', group: 'Production', field: 'sameIslandOutOfDayMalusFactor', min: 0.01, max: 1 },
  { name: 'HighDamageBonus', group: 'Production', field: 'highDamageBonus', min: 0, max: 10 },
  { name: 'MidDamageBonus', group: 'Production', field: 'midDamageBonus', min: 0, max: 10 },
  { name: 'LowDamageBonus', group: 'Production', field: 'lowDamageBonus', min: 0, max: 10 },
  { name: 'VeryLowDamageBonus', group: 'Production', field: 'veryLowDamageBonus', min: 0, max: 10 },
  { name: 'TransportBonus', group: 'Production', field: 'transportBonus', min: 0, max: 10 },
  { name: 'CurrentlyNotAttackableBonus', group: 'Production', field: 'currentlyNotAttackableBonus', min: 0, max: 10 },
  { name: 'DifferentIslandBonusInRangeDays', group: 'Production', field: 'differentIslandBonusInRangeDays', min: 1, max: 1 },
  { name: 'DifferentIslandOutOfDayMalusFactor', group: 'Production', field: 'differentIslandOutOfDayMalusFactor', min: 0.33, max: 0.33 },
  { name: 'NoTransporterBonus', group: 'Production', field: 'noTransporterBonus', min: 70, max: 70 },
  { name: 'TransporterToRequiredPlaceFactor', group: 'Production', field: 'transporterToRequiredPlaceFactor', min: 6, max: 6 },
  { name: 'MinFlyingTransportScoreForBonus', group: 'Production', field: 'minFlyingTransportScoreForBonus', min: 15, max: 15 },
  { name: 'FlyingTransporterBonus', group: 'Production', field: 'flyingTransporterBonus', min: 15, max: 15 },
  { name: 'SmallTransporterBonus', group: 'Production', field: 'smallTransporterBonus', min: 30, max: 30 },
  { name: 'UnitToSmallTransporterRatio', group: 'Production', field: 'unitToSmallTransporterRatio', min: 5, max: 5 },
  { name: 'AdditionalLoadingUnitBonus', group: 'Production', field: 'additionalLoadingUnitBonus', min: 10, max: 10 },
  { name: 'IndirectUnitAttackCountMalus', group: 'Production', field: 'indirectUnitAttackCountMalus', min: 0, max: 20 },
  { name: 'MinAttackCountBonus', group: 'Production', field: 'minAttackCountBonus', min: 0, max: 20 },
  { name: 'LowIndirectUnitBonus', group: 'Production', field: 'lowIndirectUnitBonus', min: 0, max: 100 },
  { name: 'LowIndirectMalus', group: 'Production', field: 'lowIndirectMalus', min: 0, max: 100 },
  { name: 'HighIndirectMalus', group: 'Production', field: 'highIndirectMalus', min: 0, max: 100 },
  { name: 'LowDirectUnitBonus', group: 'Production', field: 'highIndirectMalus', min: 0, max: 100 },
  { name: 'LowDirectMalus', group: 'Production', field: 'lowDirectMalus', min: 0, max: 100 },
  { name: 'HighDirectMalus', group: 'Production', field: 'highDirectMalus', min: 0, max: 100 },
  { name: 'MinUnitCountForDamageBonus', group: 'Production', field: 'minUnitCountForDamageBonus', min: 0, max: 20 },
  { name: 'CurrentlyNotAttackableScoreBonus', group: 'Production', field: 'currentlyNotAttackableScoreBonus', min: 0, max: 100 },
  { name: 'CoUnitBuffBonus', group: 'Production', field: 'coUnitBuffBonus', min: 5, max: 100 },
  { name: 'NearEnemyBonus', group: 'Production', field: 'nearEnemyBonus', min: 0, max: 100 },
  { name: 'MovementpointBonus', group: 'Production', field: 'movementpointBonus', min: 0, max: 30 },
  { name: 'DamageToUnitCostRatioBonus', group: 'Production', field: 'damageToUnitCostRatioBonus', min: 0, max: 100 },
  { name: 'SuperiorityRatio', group: 'Production', field: 'superiorityRatio', min: 1, max: 10 },
  { name: 'CheapUnitRatio', group: 'Production', field: 'cheapUnitRatio', min: 0.5, max: 2 },
  { name: 'NormalUnitRatio', group: 'Production', field: 'normalUnitRatio', min: 0.8, max: 1.2 },
  { name: 'CheapUnitValue', group: 'Production', field: 'cheapUnitValue', min: 1500, max: 5000 },
  { name: 'CheapUnitBonusMultiplier', group: 'Production', field: 'cheapUnitBonusMultiplier', min: 0, max: 100 },
  { name: 'NormalUnitBonusMultiplier', group: 'Production', field: 'normalUnitBonusMultiplier', min: 0, max: 100 },
  { name: 'ExpensiveUnitBonusMultiplier', group: 'Production', field: 'expensiveUnitBonusMultiplier', min: 0, max: 100 },
  { name: 'LowOwnBuildingEnemyBuildingRatio', group: 'Production', field: 'lowOwnBuildingEnemyBuildingRatio', min: 0, max: 10 },
  { name: 'LowInfantryRatio', group: 'Production', field: 'lowInfantryRatio', min: 0, max: 1 },
  { name: 'LowIncomeInfantryBonusMultiplier', group: 'Production', field: 'lowIncomeInfantryBonusMultiplier', min: 0, max: 100 },
  { name: 'ProducingTransportSearchrange', group: 'Production', field: 'producingTransportSearchrange', min: 6, max: 6 },
  { name: 'ProducingTransportSizeBonus', group: 'Production', field: 'producingTransportSizeBonus', min: 15, max: 15 },
  { name: 'ProducingTransportRatioBonus', group: 'Production', field: 'producingTransportRatioBonus', min: 10, max: 10 },
  { name: 'ProducingTransportLoadingBonus', group: 'Production', field: 'producingTransportLoadingBonus', min: 15, max: 15 },
  { name: 'ProducingTransportMinLoadingTransportRatio', group: 'Production', field: 'producingTransportMinLoadingTransportRatio', min: 2, max: 7 },
  { name: 'BuildingBonusMultiplier', group: 'Production', field: 'buildingBonusMultiplier', min: 0, max: 30 },
  { name: 'MinInfantryCount', group: 'Production', field: 'minInfantryCount', min: 0, max: 10 },
  { name: 'CanSupplyBonus', group: 'Production', field: 'canSupplyBonus', min: 5, max: 40 },
  { name: 'MaxSupplyUnitRatio', group: 'Production', field: 'maxSupplyUnitRatio', min: 0.01, max: 0.05 },
  { name: 'AverageSupplySupport', group: 'Production', field: 'averageSupplySupport', min: 0, max: 20 },
  { name: 'CappingFunds', group: 'Production', field: 'cappingFunds', min: 2000, max: 8000 },
  { name: 'CappedFunds', group: 'Production', field: 'cappedFunds', min: 500, max: 4000 },
  { name: 'TargetPriceDifference', group: 'Production', field: 'targetPriceDifference', min: 0, max: 1 },
  { name: 'MaxCloseDistanceDamageBonus', group: 'Production', field: 'maxCloseDistanceDamageBonus', min: 1.1, max: 10 },
  { name: 'MinCloseDistanceDamageBonus', group: 'Production', field: 'minCloseDistanceDamageBonus', min: 1.1, max: 10 },
  { name: 'SameFundsMatchUpBonus', group: 'Production', field: 'sameFundsMatchUpBonus', min: 10, max: 60 },
  { name: 'SameFundsMatchUpMovementMalus', group: 'Production', field: 'sameFundsMatchUpMovementMalus', min: 0.1, max: 1 },
  { name: 'AttackCountBonus', group: 'Production', field: 'attackCountBonus', min: 5, max: 60 },
  { name: 'MaxOverkillBonus', group: 'Production', field: 'maxOverkillBonus', min: 1.5, max: 10 },
  { name: 'CounterDamageBonus', group: 'Production', field: 'counterDamageBonus', min: 1, max: 100 },
  { name: 'EarlyGame', group: 'Production', field: 'earlyGame', min: 2, max: 10 },
  { name: 'MaxProductionBuildings', group: 'Production', field: 'maxProductionBuildings', min: 2, max: 10 },
  { name: 'LowThreadDamage', group: 'Production', field: 'lowThreadDamage', min: 1, max: 20 },
  { name: 'MaxProductionBuildingsForB', group: 'Production', field: 'maxProductionBuildingsForB', min: 1, max: 5 },
  { name: 'TurnOneDmageMalus', group: 'Production', field: 'turnOneDmageMalus', min: 1, max: 20 },
  { name: 'CounterUnitRatio', group: 'Production', field: 'counterUnitRatio', min: 1, max: 5 },
  { name: 'SpamInfantryChance', group: 'Production', field: 'spamInfantryChance', min: 100, max: 50 },
  { name: 'SameFundsMatchUpNoMatchUpValue', group: 'Production', field: 'sameFundsMatchUpNoMatchUpValue', min: 0, max: 1 },
  { name: 'SpamLightUnitChance', group: 'Production', field: 'spamLightUnitChance', min: 0, max: 100 },
  { name: 'SpamMediumUnitChance', group: 'Production', field: 'spamMediumUnitChance', min: 0, max: 100 },
  { name: 'OwnBuildingPruneRange', group: 'Production', field: 'ownBuildingPruneRange', min: 7, max: 10 },
];
