// GENERATED by tools/gen_cw_ai_groups.py -- do not edit by hand.
//
// Commander Wars' AI build groups, from resources/aidata/normal/__coreai.js.
//
// That file does not parse at upstream HEAD: line 3 writes
//   highPrioBuildings = ["FACTORY"],
// inside an object literal. The generator applies the one-character repair in
// memory to read the tables; ext/ is left untouched. See README.md for what the
// defect costs upstream.

/** One build group: what it contains and how much of the army it should be. */
export interface BuildGroup {
  /** Group name, used as the distribution key. */
  readonly name: string;
  /** Units this group may build. */
  readonly unitIds: readonly string[];
  /** Relative chance of each unit within the group; parallel to unitIds. */
  readonly chance: readonly number[];
  /** Target share of the army, before the ground/air/naval modifiers. */
  readonly distribution: number;
  /** Which build phase enables this group. */
  readonly buildMode: number;
  /** Script guard; empty for every shipped group. */
  readonly guardCondition: string;
  /** Ceiling on this group as a fraction of the army. */
  readonly maxUnitDistribution: number;
}

export const BUILD_GROUPS: Readonly<Record<string, BuildGroup>> = {
  infantryGroup: {
    name: "INFANTRY_GROUP",
    unitIds: ["INFANTRY", "MECH", "SNIPER", "MOTORBIKE", "ZCOUNIT_PARTISAN", "ZCOUNIT_COMMANDO", "ZCOUNIT_RANGER", "ZCOUNIT_AT_CYCLE"],
    chance: [70, 10, 20, 30, 10, 30, 10, 10],
    distribution: 40,
    buildMode: 0,
    guardCondition: "",
    maxUnitDistribution: 0.5,
  },
  lightTankGroup: {
    name: "LIGHT_TANK_GROUP",
    unitIds: ["LIGHT_TANK", "ARTILLERY", "ZCOUNIT_CHAPERON", "ZCOUNIT_HOT_TANK", "ZCOUNIT_SMUGGLER", "ZCOUNIT_AUTO_TANK"],
    chance: [100, 20, 20, 20, 20, 50],
    distribution: 50,
    buildMode: 1,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
  mediumTankGroup: {
    name: "MEDIUM_TANK_GROUP",
    unitIds: ["ANTITANKCANNON", "HEAVY_TANK", "ROCKETTHROWER", "ZCOUNIT_CRYSTAL_TANK", "ZCOUNIT_NEOSPIDER_TANK", "ZCOUNIT_ROYAL_GUARD", "ZCOUNIT_TANK_HUNTER"],
    chance: [30, 70, 10, 40, 40, 40, 40],
    distribution: 20,
    buildMode: 2,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
  heavyTankGroup: {
    name: "HEAVY_TANK_GROUP",
    unitIds: ["MEGATANK", "NEOTANK", "ZCOUNIT_SIEGE_CANNON", "PIPERUNNER"],
    chance: [60, 30, 60, 2],
    distribution: 10,
    buildMode: 3,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
  lightAmphibiousGroup: {
    name: "LIGHT_AMPHIBIOUS_GROUP",
    unitIds: ["ARTILLERYCRAFT", "HOVERCRAFT", "HOVERFLAK"],
    chance: [15, 80, 10],
    distribution: 40,
    buildMode: 1,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
  mediumAmphibiousGroup: {
    name: "MEDIUM_AMPHIBIOUS_GROUP",
    unitIds: ["HEAVY_HOVERCRAFT"],
    chance: [100],
    distribution: 20,
    buildMode: 2,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
  lightAirGroup: {
    name: "LIGHT_AIR_GROUP",
    unitIds: ["K_HELI", "DUSTER"],
    chance: [60, 30],
    distribution: 20,
    buildMode: 1,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
  heavyAirGroup: {
    name: "HEAVY_AIR_GROUP",
    unitIds: ["BOMBER", "STEALTHBOMBER", "ZCOUNIT_KIROV"],
    chance: [50, 25, 50],
    distribution: 10,
    buildMode: 3,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
  navalInfantryGroup: {
    name: "NAVAL_INFANTRY_GROUP",
    unitIds: ["GUNBOAT"],
    chance: [100],
    distribution: 10,
    buildMode: 0,
    guardCondition: "",
    maxUnitDistribution: 0.05,
  },
  lightNavalGroup: {
    name: "LIGHT_NAVAL_GROUP",
    unitIds: ["CANNONBOAT", "TORPEDOBOAT"],
    chance: [50, 50],
    distribution: 30,
    buildMode: 1,
    guardCondition: "",
    maxUnitDistribution: 0.2,
  },
  mediumNavalGroup: {
    name: "MEDIUM_NAVAL_GROUP",
    unitIds: ["FRIGATE", "DESTROYER", "CRUISER", "SUBMARINE"],
    chance: [30, 10, 30, 30],
    distribution: 50,
    buildMode: 2,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
  heavyNavalGroup: {
    name: "HEAVY_NAVAL_GROUP",
    unitIds: ["BATTLECRUISER", "BATTLESHIP", "AIRCRAFTCARRIER", "ZCOUNIT_MISSILE_SUB"],
    chance: [40, 40, 5, 40],
    distribution: 50,
    buildMode: 3,
    guardCondition: "",
    maxUnitDistribution: 1,
  },
};
