"""
Generates src/ai/cw/groups.ts from Commander Wars' AI build groups.

The groups live in resources/aidata/normal/__coreai.js as plain array literals:

    infantryGroup : ["INFANTRY_GROUP", [unit ids], [chances],
                     distribution, buildMode, guardCondition, maxUnitDistribution]

That file does NOT parse -- line 3 writes `highPrioBuildings = [...]` inside an
object literal, which is a syntax error, so upstream's own COREAI object fails
to load and every production callback in the shipping game throws. This script
applies that one-character repair in memory, evaluates the file with Node, and
dumps the tables. The repair is never written back to ext/.

    python3 tools/gen_cw_ai_groups.py
"""
import json
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'ext', 'Commander_Wars', 'resources', 'aidata', 'normal', '__coreai.js')
OUT = os.path.join(ROOT, 'src', 'ai', 'cw', 'groups.ts')

# The exact upstream defect, and its fix.
BROKEN = 'highPrioBuildings = ['
REPAIRED = 'highPrioBuildings : ['

GROUP_KEYS = re.compile(r'^\s*(\w*[Gg]roup)\s*:\s*\[', re.MULTILINE)


def main():
    body = open(SOURCE, encoding='utf-8', errors='replace').read()
    if BROKEN not in body:
        raise SystemExit('upstream no longer has the __coreai.js syntax error -- '
                         'check whether the repair is still needed')
    repaired = body.replace(BROKEN, REPAIRED, 1)

    names = GROUP_KEYS.findall(repaired)
    if len(names) < 8:
        raise SystemExit(f'only found {len(names)} group tables -- did __coreai.js change shape?')

    # Evaluate with Node: the tables are literals, so no game objects are needed.
    script = repaired + '\nconsole.log(JSON.stringify({' + ','.join(
        f'{n!r}: (typeof COREAI.{n} === "undefined" ? null : COREAI.{n})' for n in names) + '}));'
    result = subprocess.run(['node', '-e', script], capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f'node failed to evaluate the repaired file:\n{result.stderr}')
    groups = json.loads(result.stdout)

    lines = [
        '// GENERATED by tools/gen_cw_ai_groups.py -- do not edit by hand.',
        '//',
        "// Commander Wars' AI build groups, from resources/aidata/normal/__coreai.js.",
        '//',
        '// That file does not parse at upstream HEAD: line 3 writes',
        '//   highPrioBuildings = ["FACTORY"],',
        '// inside an object literal. The generator applies the one-character repair in',
        '// memory to read the tables; ext/ is left untouched. See README.md for what the',
        '// defect costs upstream.',
        '',
        '/** One build group: what it contains and how much of the army it should be. */',
        'export interface BuildGroup {',
        '  /** Group name, used as the distribution key. */',
        '  readonly name: string;',
        '  /** Units this group may build. */',
        '  readonly unitIds: readonly string[];',
        '  /** Relative chance of each unit within the group; parallel to unitIds. */',
        '  readonly chance: readonly number[];',
        '  /** Target share of the army, before the ground/air/naval modifiers. */',
        '  readonly distribution: number;',
        '  /** Which build phase enables this group. */',
        '  readonly buildMode: number;',
        '  /** Script guard; empty for every shipped group. */',
        '  readonly guardCondition: string;',
        '  /** Ceiling on this group as a fraction of the army. */',
        '  readonly maxUnitDistribution: number;',
        '}',
        '',
        'export const BUILD_GROUPS: Readonly<Record<string, BuildGroup>> = {',
    ]
    kept = 0
    for name, value in groups.items():
        if not value or len(value) < 7:
            continue
        kept += 1
        group, unit_ids, chance, distribution, build_mode, guard, max_dist = value[:7]
        lines.append(f'  {name}: {{')
        lines.append(f'    name: {json.dumps(group)},')
        lines.append(f'    unitIds: {json.dumps(list(unit_ids))},')
        lines.append(f'    chance: {json.dumps(list(chance))},')
        lines.append(f'    distribution: {distribution},')
        lines.append(f'    buildMode: {build_mode},')
        lines.append(f'    guardCondition: {json.dumps(guard)},')
        lines.append(f'    maxUnitDistribution: {max_dist},')
        lines.append('  },')
    lines += ['};', '']

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8').write('\n'.join(lines))
    print(f'{kept} build groups -> {OUT}')


if __name__ == '__main__':
    main()
