"""Emit the pinned NormalAi production policy for the browser, with its syntax repair.

The policy is deliberately copied, not reimplemented: counter queues, funds
phases and topology updates must stay tied to the same upstream revision.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'ext/Commander_Wars/resources/aidata/normal/__coreai.js'
OUT = ROOT / 'src/ai/cw/production-policy.ts'


def main():
    body = SOURCE.read_text()
    broken = 'highPrioBuildings = ['
    if body.count(broken) != 1:
        raise SystemExit('Review upstream production policy: expected syntax defect changed')
    body = body.replace(broken, 'highPrioBuildings : [', 1)
    OUT.write_text('// @ts-nocheck\n// GENERATED by tools/gen_cw_production_policy.py; do not edit.\n'
                   '// Pinned Commander Wars __coreai.js, with only its object-literal syntax repaired.\n'
                   "import { GameEnums } from '../../host/enums.ts';\n\n" + body + '\nexport { COREAI as PRODUCTION_POLICY };\n')
    print(OUT)


if __name__ == '__main__':
    main()
