"""
Generates src/ai/cw/config.ts from Commander Wars' own AI tunables.

The 140 knobs NormalAi reads are declared twice upstream: as defaults with
mutation bounds in the m_iniData table in ai/normalai.cpp, and as overrides in
resources/aidata/normal/*.ini. Transcribing that by hand would be 140 chances
to fat-finger a constant, and it would go stale the moment ext/ is updated.

    .venv/bin/python tools/gen_cw_ai_config.py

Re-run after pulling ext/Commander_Wars. The output is checked in so the browser
build needs no file IO and the values are reviewable in a diff.
"""
import configparser
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CW = os.path.join(ROOT, 'ext', 'Commander_Wars')
SOURCE = os.path.join(CW, 'ai', 'normalai.cpp')
PROFILE = os.path.join(CW, 'resources', 'aidata', 'normal', 'normal.ini')
OUT = os.path.join(ROOT, 'src', 'ai', 'cw', 'config.ts')

ENTRY = re.compile(
    r'\{\s*"(?P<name>\w+)"\s*,\s*"(?P<group>\w+)"\s*,\s*&m_(?P<field>\w+)\s*,'
    r'\s*(?P<default>-?[\d.]+)f?\s*,\s*(?P<min>-?[\d.]+)f?\s*,\s*(?P<max>-?[\d.]+)f?\s*\}')


def ini_section(profile, group):
    """
    Qt's on-disk name for the section the C++ asks for.

    QSettings reserves the top-level "General" section for ungrouped keys, so a
    user group actually called General is written as [%General]. Reading the
    literal name finds nothing and every [%General] override is silently lost --
    which is 15 of NormalAi's knobs, including DirectIndirectRatio.
    """
    for candidate in (group, '%' + group):
        if profile.has_section(candidate):
            return candidate
    return None


def camel(field):
    """m_ProducingTransportSizeBonus -> producingTransportSizeBonus."""
    return field[0].lower() + field[1:]


def number(text):
    value = float(text)
    return str(int(value)) if value == int(value) else repr(value)


def main():
    body = open(SOURCE, encoding='utf-8', errors='replace').read()
    block = body[body.index('m_iniData = {'):]
    block = block[:block.index('\n    };')]
    entries = [m.groupdict() for m in ENTRY.finditer(block)]
    # NormalAi's table is the only one: SimpleProductionSystem has no m_iniData of
    # its own and reads the [Production] group through these same fields. The .ini
    # carries a few keys absent from the table, which upstream's readIni ignores.
    if len(entries) < 120:
        raise SystemExit(f'only parsed {len(entries)} ini entries -- did normalai.cpp change shape?')

    profile = configparser.ConfigParser()
    profile.optionxform = str            # keys are CamelCase upstream
    profile.read(PROFILE, encoding='utf-8')

    # readIni walks m_iniData in order and writes through the entry's pointer, so
    # when two names share a field the later one wins. That is not hypothetical:
    # upstream declares LowDirectUnitBonus against &m_highIndirectMalus, so the
    # ini's LowDirectUnitBonus silently overwrites HighIndirectMalus. Applying the
    # overrides in declaration order reproduces the value the C++ actually runs on.
    values, aliased = {}, {}
    for entry in entries:
        field = camel(entry['field'])
        values.setdefault(field, float(entry['default']))
        name = entry['name']
        group = ini_section(profile, entry['group'])
        if group is not None and profile.has_option(group, name):
            values[field] = profile.getfloat(group, name)
            aliased.setdefault(field, []).append(name)

    shared = {f: names for f, names in aliased.items() if len(names) > 1}
    fields = sorted({camel(e['field']) for e in entries})

    lines = [
        '// GENERATED by tools/gen_cw_ai_config.py -- do not edit by hand.',
        '//',
        "// Commander Wars' NormalAi tunables: defaults from the m_iniData table in",
        '// ai/normalai.cpp, overridden by resources/aidata/normal/normal.ini, which is',
        '// the profile the shipping game plays on.',
        '',
        '/** One tunable, with the bounds randomize() mutates it between. */',
        'export interface IniRange {',
        '  /** Key as it appears in the .ini file. */',
        '  readonly name: string;',
        '  /** .ini section. */',
        '  readonly group: string;',
        '  /** Field on NormalAiConfig this writes through to. */',
        '  readonly field: keyof NormalAiConfig;',
        '  readonly min: number;',
        '  readonly max: number;',
        '}',
        '',
        'export interface NormalAiConfig {',
    ]
    for field in fields:
        lines.append(f'  {field}: number;')
    lines += ['}', '']

    if shared:
        lines += [
            '/**',
            ' * Upstream aliases these .ini keys onto one field, so the last one read wins:',
        ]
        for field, names in sorted(shared.items()):
            lines.append(f' *   {field} <- {", ".join(names)}')
        lines += [
            ' *',
            ' * That is an upstream pointer mix-up rather than a design, but the shipping',
            ' * game plays on the resulting value, so the port keeps it.',
            ' */',
        ]
    lines += ['export const NORMAL_AI_DEFAULTS: NormalAiConfig = {']
    for field in fields:
        lines.append(f'  {field}: {number(str(values[field]))},')
    lines += ['};', '']

    lines += [
        '/**',
        ' * Mutation bounds, straight from the C++ table.',
        ' *',
        ' * CoreAI::randomizeIni rolls each knob inside its range to make a family of',
        ' * distinct opponents out of one AI. Note a few upstream ranges are degenerate',
        ' * (min above max, defaults outside the range); they are transcribed as-is and',
        ' * randomize() orders each pair before sampling.',
        ' */',
        'export const INI_RANGES: readonly IniRange[] = [',
    ]
    for entry in entries:
        lines.append(
            f"  {{ name: '{entry['name']}', group: '{entry['group']}', "
            f"field: '{camel(entry['field'])}', "
            f"min: {number(entry['min'])}, max: {number(entry['max'])} }},")
    lines += ['];', '']

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8').write('\n'.join(lines))
    overridden = sum(len(n) for n in aliased.values())
    print(f'{len(entries)} entries -> {len(fields)} fields, '
          f'{overridden} overridden by normal.ini, {len(shared)} aliased')
    for field, names in sorted(shared.items()):
        print(f'  aliased: {field} <- {names}')
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
